# Site settings
author: Joann Pan
title: Joann's Coding Journey
header-img: img/home-bg.png
email: joannlpan@gmail.com
copyright_name: Joann Pan
description: > # this means to ignore newlines until "baseurl:"
  Because it's time to join the real world of computers
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JLPinthecity

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
